"""Building screen: shows the last robot generated by the build tool."""

from __future__ import annotations

from textual.app import ComposeResult
from textual.binding import Binding
from textual.widget import Widget
from textual.widgets import RichLog


class BuildingScreen(Widget):
    """Displays the most recently built robot's info and validation status."""

    BINDINGS = [
        Binding("ctrl+l", "clear_log", "Clear"),
    ]

    def compose(self) -> ComposeResult:
        yield RichLog(id="log", wrap=True, markup=True, highlight=False)

    def on_mount(self) -> None:
        log = self.query_one("#log", RichLog)
        log.write("[dim]No robot built yet. Use the Chat tab to generate a robot.[/dim]")

    def refresh_display(self, result: dict) -> None:
        """Update the log with info from a generate_robot tool result."""
        log = self.query_one("#log", RichLog)
        log.clear()

        robot_name = result.get("robot_name", "unknown")
        fmt = result.get("format", "mjcf")
        status = "[bold green]PASS[/bold green]" if result.get("success") else "[bold red]FAIL[/bold red]"

        model_info = result.get("model_info", {})
        bodies = model_info.get("num_bodies", "?")
        joints = model_info.get("num_joints", "?")
        actuators = model_info.get("num_actuators", "?")

        buildability = result.get("buildability", {})
        feasible = buildability.get("feasible", "unknown")

        log.write(f"[bold]Robot:[/bold] {robot_name}  [bold]Format:[/bold] {fmt}")
        log.write(f"[bold]Validation:[/bold] {status}")
        log.write(
            f"[bold]Bodies:[/bold] {bodies}  "
            f"[bold]Joints:[/bold] {joints}  "
            f"[bold]Actuators:[/bold] {actuators}"
        )
        log.write(f"[bold]Buildability:[/bold] {feasible}")

        actuator_assignments = result.get("actuator_assignments", {})
        if actuator_assignments:
            log.write("\n[bold]Actuator Assignments:[/bold]")
            for joint, actuator in actuator_assignments.items():
                log.write(f"  {joint}: {actuator}")

        material_assignments = result.get("material_assignments", {})
        if material_assignments:
            log.write("\n[bold]Material Assignments:[/bold]")
            for part, material in material_assignments.items():
                log.write(f"  {part}: {material}")

    def action_clear_log(self) -> None:
        self.query_one("#log", RichLog).clear()
