"""W5 — Quasi-static tipping decomposition (Isaac Lab, WSL-only).

For each of six controller-field combinations (lean / retract / push and
pairs / triplet) this test:

  1. Builds a single-env `UrchinEnv` from canonical reset cfg.
  2. Resets to identity orientation, zero velocity, zero panel state.
  3. Slowly ramps the field amplitude(s) from 0 -> 1 over 1.0 s with
     phase_velocity_hz=0 (DC / quasi-static), then holds for 0.5 s.
  4. Samples body pose, body angular velocity, and panel contact state at
     60 Hz throughout the 1.5 s window.
  5. Writes per-step rows to
     `workspace/_tasks_out/w5_tipping/<condition>.csv` and a single
     summary row (tip_onset_angle_deg, tip_margin_max,
     contact_set_change, net_forward_rotation_rad) to
     `workspace/_tasks_out/w5_tipping/summary.csv`.

Acceptance gate is in `workspace/_tasks_out/w5_tipping/report.md`
generated by `workspace/scratch/w5_postprocess.py` after all six
conditions have been collated.

Why one condition per pytest invocation:
  Isaac Lab's `Articulation` cannot cheaply be torn down + re-created
  inside a single Python process — the underlying USD stage and
  `SimulationContext` carry state that only `AppLauncher` cleanly
  initializes. To get a *fresh articulation* per condition (the spec's
  hard requirement), the driver `scripts/run_urchin_v3_tipping_decomp.sh`
  invokes pytest six times, once per condition, with the env var
  `URCHIN_W5_CONDITION` selecting the field combination. This file
  collects only the single condition specified by that env var.

Why this test is Linux-only:
  Isaac Sim only ships on Linux (we run it inside WSL2). On Windows
  (no `isaaclab.app` importable) the module-level `pytestmark` skip
  fires before any heavy import is attempted.

Reference: `docs/Urchin-deep-research-report.md` §"Experimental Plan",
Table row 3 (six-condition tipping decomposition).
"""
from __future__ import annotations

import csv
import math
import os
import sys
from pathlib import Path

import pytest


# ---------------------------------------------------------------------------
# Capability detection (no hard Isaac Lab import at module top).
#
# Mirrors the pattern used by W4's test_actuator_response.py /
# test_friction_map.py — pytest collection on Windows must NOT trip on
# isaaclab / cuda imports, but tests should be visible in --collect-only.
# Windows is also gated implicitly: isaaclab is Linux-only.
# ---------------------------------------------------------------------------


def _has_isaaclab() -> bool:
    try:
        from isaaclab.app import AppLauncher  # noqa: F401
        return True
    except Exception:
        return False


pytestmark = pytest.mark.skipif(
    not _has_isaaclab(),
    reason="W5 tipping decomposition requires Isaac Lab (run inside WSL2).",
)


# Stdlib + non-Isaac imports.
import json  # noqa: E402

import torch  # noqa: E402


# ---------------------------------------------------------------------------
# Conditions (research report Table row 3)
# ---------------------------------------------------------------------------

CONDITIONS = {
    # name           : (rear_push_amp, front_reach_amp, front_retract_amp)
    "lean_only":      (0.0, 1.0, 0.0),
    "retract_only":   (0.0, 0.0, 1.0),
    "push_only":      (1.0, 0.0, 0.0),
    "lean_retract":   (0.0, 1.0, 1.0),
    "retract_push":   (1.0, 0.0, 1.0),
    "full_triplet":   (1.0, 1.0, 1.0),
}


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

OUT_DIR = (
    Path(__file__).resolve().parents[2]
    / "workspace" / "_tasks_out" / "w5_tipping"
)
RAMP_S = 1.0          # 0 -> 1 amplitude ramp duration (seconds)
HOLD_S = 0.5          # steady-state hold duration after ramp
TOTAL_S = RAMP_S + HOLD_S
SAMPLE_HZ = 60.0      # bookkeeping frequency
TIP_OMEGA_THRESHOLD = 0.1  # |angular vel| (rad/s) for tip-onset detection
CONTACT_DEFLECTION_BIN = 0.0005   # binarize threshold (metres) on spring deflection
SEED = 42

# Effective rolling radius for the urchin v3 shell. Used only in this
# test to project body angular velocity onto the rolling axis. Pulled
# from the deep-research report; matches DEFAULT_RADIUS conventions
# used elsewhere in the codebase.
SHELL_RADIUS_M = 0.17


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _select_condition() -> tuple[str, tuple[float, float, float]]:
    """Pick the condition this pytest invocation is responsible for.

    Single source of truth: env var `URCHIN_W5_CONDITION`. If unset,
    skip with a message; the driver script always sets it.
    """
    name = os.environ.get("URCHIN_W5_CONDITION", "").strip()
    if not name:
        pytest.skip(
            "URCHIN_W5_CONDITION not set; this test runs one condition "
            "per pytest invocation. Use scripts/run_urchin_v3_tipping_decomp.sh.",
            allow_module_level=False,
        )
    if name not in CONDITIONS:
        pytest.skip(
            f"Unknown URCHIN_W5_CONDITION={name!r}; "
            f"expected one of {sorted(CONDITIONS)}.",
            allow_module_level=False,
        )
    return name, CONDITIONS[name]


def _quat_to_z_tilt_deg(quat_wxyz: torch.Tensor) -> float:
    """Angle of body Z-axis from world Z (+up) in degrees.

    Input: (4,) quaternion (w, x, y, z). At identity orientation
    returns 0; tipping rotates the body Z away from world +Z.
    """
    w, x, y, z = (float(quat_wxyz[i]) for i in range(4))
    # body z-axis in world frame, rotated by quat:
    #   z_w = R(q) @ [0, 0, 1]
    # third column of the rotation matrix:
    zx = 2.0 * (x * z + w * y)
    zy = 2.0 * (y * z - w * x)
    zz = 1.0 - 2.0 * (x * x + y * y)
    cos_tilt = max(-1.0, min(1.0, zz))
    return math.degrees(math.acos(cos_tilt))


# ---------------------------------------------------------------------------
# The test
# ---------------------------------------------------------------------------

def test_tipping_decomposition_one_condition(tmp_path):
    """Run one of the six tipping conditions end-to-end."""
    cond_name, (rear_amp, lean_amp, retract_amp) = _select_condition()

    # ---- Boot Isaac Lab ----------------------------------------------------
    # Force canonical reset + clean physics + zero oracle / full residual.
    # These env vars must be set BEFORE importing urchin_env_cfg, since the
    # config dataclass reads them at module import time.
    os.environ.setdefault("URCHIN_RESET_MODE", "canonical")
    os.environ.setdefault("URCHIN_ORACLE_AMPLITUDE", "0.0")
    os.environ.setdefault("URCHIN_RESIDUAL_SCALE_INIT", "1.0")
    os.environ.setdefault("URCHIN_RESIDUAL_SCALE_FINAL", "1.0")

    from isaaclab.app import AppLauncher  # type: ignore

    app_launcher = AppLauncher({"headless": True})
    sim_app = app_launcher.app  # noqa: F841 — held for the env's lifetime

    try:
        # urchin_v3 expects to import as a package; add scripts/ to sys.path
        # for rolling_engine, and the urchin_v3 parent for the env package.
        repo_root = Path(__file__).resolve().parents[2]
        v3_root = repo_root / "workspace" / "robots" / "urchin_v3"
        v3_scripts = v3_root / "scripts"
        for p in (v3_root, v3_scripts):
            if str(p) not in sys.path:
                sys.path.insert(0, str(p))

        import rolling_engine as roll  # type: ignore
        from scripted_roll import build_sh_basis  # type: ignore
        from urchin_v3.urchin_env_cfg import UrchinEnv, UrchinEnvCfg  # type: ignore

        torch.manual_seed(SEED)

        cfg = UrchinEnvCfg()
        cfg.scene.num_envs = 1
        # Sanity: confirm we got the canonical reset path.
        assert cfg.reset_mode == "canonical", (
            f"expected canonical reset, got {cfg.reset_mode!r}; "
            "URCHIN_RESET_MODE must be set before importing urchin_env_cfg."
        )

        env = UrchinEnv(cfg)
        device = env.device
        dt = float(env.cfg.sim.dt) * env.cfg.decimation  # env-step dt

        # Trigger first reset so internal buffers (B, panel_joint_ids) populate.
        obs, _ = env.reset()
        # _smoothed_targets only exists after one pre-physics step; force one
        # zero-action step so subsequent indexing is safe.
        zero_action = torch.zeros(1, env.cfg.action_space, device=device)
        env.step(zero_action)
        obs, _ = env.reset()

        # ---- Engine config for this condition -----------------------------
        engine_cfg = roll.RollingEngineCfg(
            rear_push_amp=rear_amp,
            front_reach_amp=lean_amp,
            front_retract_amp=retract_amp,
            phase_velocity_hz=0.0,    # DC / quasi-static (per spec)
            push_duty=1.0,
            lean_duty=1.0,
            retract_duty=1.0,
            push_phase=0.0,
            lean_phase=0.0,
            retract_phase=0.0,
        )
        engine_state = roll.new_state(num_envs=1, device=device)

        axes_b = env._axes_b  # (42, 3) body-frame panel normals
        B = build_sh_basis(axes_b).to(device)              # (42, 9)
        # Pseudoinverse of B used to project 42-panel raw -> 9-D SH.
        B_pinv = torch.linalg.pinv(B).to(device)           # (9, 42)

        # Sample stride: env step dt is fixed; pick the integer sample stride
        # closest to (1/SAMPLE_HZ). Number of env steps in 1.5 s is
        # ceil(TOTAL_S / dt). We log every step (60 Hz env step ~= dt 0.0167s
        # at decimation=4 over 240Hz physics).
        total_steps = int(math.ceil(TOTAL_S / dt))

        # Capture initial pose / contact set for the reference frame.
        robot = env.scene["robot"]
        init_quat = robot.data.root_quat_w[0].detach().cpu().clone()  # (4,)
        init_panel_pos = robot.data.joint_pos[
            0, env._panel_joint_ids_t
        ].detach().cpu().clone()  # (42,)

        # ---- Per-step rollout + sample buffers ----------------------------
        rows = []  # list of per-step dicts

        # Goal direction in body frame. Engine wants a forward direction;
        # use +x so steering_bias=0 keeps the controller aligned with the
        # "world +x" intent. The ramping happens via the amplitude scalars,
        # not the goal vector.
        to_goal_b = torch.tensor(
            [[1.0, 0.0]], device=device, dtype=torch.float32,
        )

        contact_init_bin = None  # set on first step

        for step_i in range(total_steps):
            t = step_i * dt
            # Linear ramp from 0->1 over RAMP_S, hold at 1 for HOLD_S.
            ramp = min(1.0, t / RAMP_S) if RAMP_S > 0 else 1.0

            # Build a per-step engine cfg with ramped amplitudes.
            ramped_cfg = roll.RollingEngineCfg(
                rear_push_amp=rear_amp * ramp,
                front_reach_amp=lean_amp * ramp,
                front_retract_amp=retract_amp * ramp,
                phase_velocity_hz=0.0,
                push_duty=1.0,
                lean_duty=1.0,
                retract_duty=1.0,
            )

            gravity_b = robot.data.projected_gravity_b   # (1, 3)
            sh_action = roll.forward_sh_coeffs(
                axes_b=axes_b,
                projected_gravity_b=gravity_b,
                to_goal_b=to_goal_b,
                state=engine_state,
                cfg=ramped_cfg,
                B_pinv=B_pinv,
            )                                            # (1, 9)

            obs, _, _, _, _ = env.step(sh_action)

            # ---- Sample state for this step --------------------------------
            root_pos = robot.data.root_pos_w[0].detach().cpu().numpy()
            quat = robot.data.root_quat_w[0].detach().cpu()  # (4,)
            ang_vel_w = robot.data.root_ang_vel_w[0].detach().cpu().numpy()
            lin_vel_w = robot.data.root_lin_vel_w[0].detach().cpu().numpy()
            panel_pos = robot.data.joint_pos[
                0, env._panel_joint_ids_t
            ].detach().cpu()
            # Per-panel deflection = max(target - pos, 0) — the same proxy
            # the env uses for "contact" in obs.
            smoothed_targets = env._smoothed_targets[0].detach().cpu()
            deflection = (smoothed_targets - panel_pos).clamp(min=0.0)
            contact_bin = (deflection > CONTACT_DEFLECTION_BIN).to(torch.int8)

            if contact_init_bin is None:
                contact_init_bin = contact_bin.clone()

            tilt_deg = _quat_to_z_tilt_deg(quat)
            ang_vel_mag = float(
                math.sqrt(float(
                    ang_vel_w[0] ** 2 + ang_vel_w[1] ** 2 + ang_vel_w[2] ** 2
                )),
            )

            # Project body angular velocity onto the rolling axis ( y_world,
            # since to_goal_b = +x and gravity = -z, rolling-axis = z X x = y ).
            omega_roll = float(ang_vel_w[1])

            # Approximate forward-COM bias d_f and forward support s_f
            # for the tip-margin metric. Both are body-frame scalars
            # measured in metres along the goal direction.
            #   d_f = projection of root COM displacement onto goal
            #         direction (proxy for forward COM bias from neutral).
            #   s_f = forward extent of the panel-contact polygon along
            #         the goal direction (proxy for support-boundary).
            forward_w = torch.tensor([1.0, 0.0, 0.0])  # goal direction in world
            com_xy = torch.tensor([
                float(root_pos[0]),
                float(root_pos[1]),
            ])
            d_f = float(com_xy[0])  # COM forward displacement from spawn (x=0)

            # Forward support extent: the maximum forward projection of any
            # contacting panel's normal axis. Panel normals are body-frame;
            # rotate to world using root_quat and then project onto fwd.
            from isaaclab.utils.math import quat_apply  # type: ignore
            quat_b = robot.data.root_quat_w[0:1]            # (1, 4)
            axes_w = quat_apply(
                quat_b.expand(axes_b.shape[0], -1), axes_b,
            )                                                # (42, 3)
            # Forward projection of *contacting* panels only.
            f_proj = (axes_w[:, 0]).detach().cpu()           # (42,)
            contact_mask = contact_bin.to(torch.bool)
            if contact_mask.any():
                s_f = float(f_proj[contact_mask].max().item()) * SHELL_RADIUS_M
            else:
                s_f = 0.0

            tip_margin = d_f - s_f

            rows.append({
                "step": step_i,
                "t_s": t,
                "ramp": ramp,
                "tilt_deg": tilt_deg,
                "ang_vel_mag": ang_vel_mag,
                "omega_roll": omega_roll,
                "lin_vel_x": float(lin_vel_w[0]),
                "lin_vel_y": float(lin_vel_w[1]),
                "lin_vel_z": float(lin_vel_w[2]),
                "com_x": float(root_pos[0]),
                "com_y": float(root_pos[1]),
                "com_z": float(root_pos[2]),
                "d_f": d_f,
                "s_f": s_f,
                "tip_margin": tip_margin,
                "n_contact": int(contact_bin.sum().item()),
            })

        # ---- Per-condition summary ----------------------------------------
        # tip_onset_angle_deg: tilt at first step where |ang_vel| > threshold.
        tip_onset = None
        for r in rows:
            if r["ang_vel_mag"] > TIP_OMEGA_THRESHOLD:
                tip_onset = r["tilt_deg"]
                break
        tip_onset_angle_deg = (
            float("nan") if tip_onset is None else float(tip_onset)
        )

        tip_margin_max = max(r["tip_margin"] for r in rows)

        # contact_set_change: |XOR(contact_bin_init, contact_bin_final)|
        final_contact_bin = (
            (env._smoothed_targets[0]
             - robot.data.joint_pos[0, env._panel_joint_ids_t])
            .clamp(min=0.0)
            .detach().cpu()
            > CONTACT_DEFLECTION_BIN
        ).to(torch.int8)
        contact_set_change = int(
            (contact_init_bin != final_contact_bin).sum().item()
        )

        # net_forward_rotation_rad = ∫ omega_roll dt over [0, total_s].
        net_rot = 0.0
        for r in rows:
            net_rot += r["omega_roll"] * dt
        net_forward_rotation_rad = float(net_rot)

        # ---- Persist artifacts --------------------------------------------
        OUT_DIR.mkdir(parents=True, exist_ok=True)

        per_step_path = OUT_DIR / f"{cond_name}.csv"
        with per_step_path.open("w", newline="") as fp:
            writer = csv.DictWriter(fp, fieldnames=list(rows[0].keys()))
            writer.writeheader()
            writer.writerows(rows)

        # Append (or initialize) the summary CSV. We append because each
        # pytest invocation only handles one condition; the driver script
        # truncates the file before the loop.
        summary_path = OUT_DIR / "summary.csv"
        is_new = not summary_path.exists()
        with summary_path.open("a", newline="") as fp:
            writer = csv.writer(fp)
            if is_new:
                writer.writerow([
                    "condition",
                    "rear_push_amp",
                    "front_reach_amp",
                    "front_retract_amp",
                    "tip_onset_angle_deg",
                    "tip_margin_max",
                    "contact_set_change",
                    "net_forward_rotation_rad",
                ])
            writer.writerow([
                cond_name,
                rear_amp,
                lean_amp,
                retract_amp,
                f"{tip_onset_angle_deg:.6f}",
                f"{tip_margin_max:.6f}",
                contact_set_change,
                f"{net_forward_rotation_rad:.6f}",
            ])

        # Also drop a per-condition JSON for the post-processor (avoids any
        # reliance on CSV column ordering downstream).
        cond_json_path = OUT_DIR / f"{cond_name}.json"
        cond_json_path.write_text(json.dumps({
            "condition": cond_name,
            "rear_push_amp": rear_amp,
            "front_reach_amp": lean_amp,
            "front_retract_amp": retract_amp,
            "metrics": {
                "tip_onset_angle_deg": tip_onset_angle_deg,
                "tip_margin_max": tip_margin_max,
                "contact_set_change": contact_set_change,
                "net_forward_rotation_rad": net_forward_rotation_rad,
            },
            "params": {
                "ramp_s": RAMP_S,
                "hold_s": HOLD_S,
                "sample_hz": SAMPLE_HZ,
                "dt_env_step": dt,
                "tip_omega_threshold": TIP_OMEGA_THRESHOLD,
                "contact_deflection_bin": CONTACT_DEFLECTION_BIN,
                "shell_radius_m": SHELL_RADIUS_M,
                "seed": SEED,
            },
        }, indent=2))

        env.close()
    finally:
        # AppLauncher shutdown — best-effort. Some Isaac builds expose
        # `sim_app.close()`; older ones rely on process exit.
        try:
            sim_app.close()
        except Exception:
            pass
